title:            ccBrain Lab
description:      Cognition and Computational Brain Lab

# put your disqus here
disqus_shortname: 
reading_time:     false # if true, shows the estimated reading time for a post
words_per_minute: 200
logo:             images/logo_web.svg # logo visible in the topbar
excerpt_separator: <!--more-->
# Your site's domain goes here (eg: //mmistakes.github.io, http://mademistakes.com, etc)
# When testing locally leave blank or use http://localhost:4000

url: "https://ccbrain.org"

# draw your top menu here
# each item must have a title and a url.
#   To list post categories. use type: 'categories'
#   To create sub categories. add a submenu item
# See the example
menu: 
  - title:  'People'
    url:    '/people'
    submenu:
        - title: 'Current member'
          url: '/people'
        - title: 'Alumni'
          url: '/people/alumni'
  - title:  'Research'
    url:    '/research'
  - title:  'Publications'
    url:    '/publications'
  - title:  'Join'
    url:    '/join'
  - title:  'Stuff'
    url:    '/updates'
    submenu:
        - title: 'Updates'
          url: '/updates'
        - title: 'Contact'
          url: '/#contact'
  #- title: 'Stuff'
  #  url: '/categories'
  #  type: 'categories'        
  #-  url: '/tags'
  #- title: 'Tags'
  #  url: '/tags'  
  #- title: 'Categories'
  #  url: '/categories'
  #  type: 'categories'
  #- title: 'Favorites'
  #  url: '#'
  #  submenu:
  #    - title: 'Code Highlighter'
  #      url: '/intro/code-highlighting-post/'
  #    - title: 'Sample Post'
  #      url: '/intro/sample-post/'

# Owner/author information
owner:
  name:           Jiaxiang Zhang
  site:           https://ccbrain.org
  avatar:         images/avatar.jpg
  bio:            "ccBrain Lab"
  email:          zhangj73@cardiff.ac.uk
  # Twitter nick for use in Twitter cards and follow button.
  twitter:        ccbrainlab   # if no twitter in this config, the twitter follow button will be removed
  # GitHub nick for use in follow button in author block.
  github:         ccbrain

# Twitter account associated with the site if different from owner/author twitter account.
# Used in Twitter cards.
twitter:

# Social networking links used in author block underneath posts. Update and remove as you like.
social:
  - title:  "github"
    url:    "https://github.com/ccbrain"
  - title:  "linkedin"
    url:    "https://uk.linkedin.com/in/jiaxiang"

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
locale:      en_UK
future:      true
highlighter: rouge
markdown:    kramdown
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
#paginate: 5

# if true, shows the floatting share buttons
float_share: true

# Octopress
# Default extensions
post_ext: md
page_ext: md

# Format titles with titlecase?
titlecase: true

include: [".htaccess"]
exclude: ["demo/*", "lib", "config.rb", "Capfile", "config", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]
# gems:    [jekyll-paginate]
# theme: neo-hpstr-jekyll-theme

#gems:
#  - jekyll-sitemap

#repository: henry/henrydf.github.io
paginate: 5
paginate_path: "/updates/page:num/"

colors:  #in hex code if not noted else
  primary: "#00b3fe" #"#F70031"
  primary_rgb: "0,179,254" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#222222" #"#384452" #"#33004D"
  link: "#428bca"
  link_hover: "#01b2fe"
  footer_heading: "#ffffff"
  footer_content: "#ffffff"

# Scopes
defaults: 
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         "_people"
      type:         "people"
    values:
      layout:       "profile"
      
collections:
  people:
    output: true
    permalink: /people/:title/index.html

    
prose:
  rooturl: '_posts'
  media: 'images'
  metadata:
    _posts:
      - name: "title"
        field:
            element: "text"
            label: "Title"
            value: ""
      - name: "author"
        field:
            element: "text"
            label: "Author"
      - name: "published"
        field:
            element: "hidden"
            label: "Published"
            value: true
      - name: "categories"
        field:
            element: "select"
            label: "Select Category"
            placeholder: "Choose Category"
            options:
            - name: "General"
              value: "general"
            - name: "Science"
              value: "science"
      - name: "permalink"
        field:
            element: "text"
            label: "Relative URL"
            help: "provide a url relative to site url, for eg. /getting-started/blog1"
            
gems:
  - jekyll-sitemap
  - jekyll-paginate
